ALTER TABLE projects ADD COLUMN IF NOT EXISTS image_url VARCHAR(512);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS github_url VARCHAR(512);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS technologies TEXT;
